// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: api/protoc/entity/workload_spec_message.proto

package entity

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WorkloadSpec_Isolation int32

const (
	WorkloadSpec_NO_ISOLATION        WorkloadSpec_Isolation = 0
	WorkloadSpec_CONTAINER_ISOLATION WorkloadSpec_Isolation = 1
	WorkloadSpec_KERNEL_ISOLATION    WorkloadSpec_Isolation = 2
)

// Enum value maps for WorkloadSpec_Isolation.
var (
	WorkloadSpec_Isolation_name = map[int32]string{
		0: "NO_ISOLATION",
		1: "CONTAINER_ISOLATION",
		2: "KERNEL_ISOLATION",
	}
	WorkloadSpec_Isolation_value = map[string]int32{
		"NO_ISOLATION":        0,
		"CONTAINER_ISOLATION": 1,
		"KERNEL_ISOLATION":    2,
	}
)

func (x WorkloadSpec_Isolation) Enum() *WorkloadSpec_Isolation {
	p := new(WorkloadSpec_Isolation)
	*p = x
	return p
}

func (x WorkloadSpec_Isolation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadSpec_Isolation) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protoc_entity_workload_spec_message_proto_enumTypes[0].Descriptor()
}

func (WorkloadSpec_Isolation) Type() protoreflect.EnumType {
	return &file_api_protoc_entity_workload_spec_message_proto_enumTypes[0]
}

func (x WorkloadSpec_Isolation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadSpec_Isolation.Descriptor instead.
func (WorkloadSpec_Isolation) EnumDescriptor() ([]byte, []int) {
	return file_api_protoc_entity_workload_spec_message_proto_rawDescGZIP(), []int{0, 0}
}

type WorkloadSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,min=1,unique=Name,dive,required"
	Containers []*WorkloadSpec_Container `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty" validate:"required,min=1,unique=Name,dive,required"`
	// @inject_tag: validate:"required"
	Isolation WorkloadSpec_Isolation `protobuf:"varint,3,opt,name=isolation,proto3,enum=io.naftis.entity.WorkloadSpec_Isolation" json:"isolation,omitempty" validate:"required"`
	// @inject_tag: validate:"required"
	NodeSelector []*NodeSelector `protobuf:"bytes,4,rep,name=nodeSelector,proto3" json:"nodeSelector,omitempty" validate:"required"`
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protoc_entity_workload_spec_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoc_entity_workload_spec_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_api_protoc_entity_workload_spec_message_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadSpec) GetContainers() []*WorkloadSpec_Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *WorkloadSpec) GetIsolation() WorkloadSpec_Isolation {
	if x != nil {
		return x.Isolation
	}
	return WorkloadSpec_NO_ISOLATION
}

func (x *WorkloadSpec) GetNodeSelector() []*NodeSelector {
	if x != nil {
		return x.NodeSelector
	}
	return nil
}

type WorkloadSpec_Container struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,printascii"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required,printascii"`
	// @inject_tag: validate:"required,printascii"
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty" validate:"required,printascii"`
	// @inject_tag: validate:"required"
	Resources *WorkloadSpec_Container_Resources `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty" validate:"required"`
	// @inject_tag: validate:"max=10"
	Storage []*WorkloadSpec_Container_Storage `protobuf:"bytes,4,rep,name=storage,proto3" json:"storage,omitempty" validate:"max=10"`
}

func (x *WorkloadSpec_Container) Reset() {
	*x = WorkloadSpec_Container{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protoc_entity_workload_spec_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadSpec_Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec_Container) ProtoMessage() {}

func (x *WorkloadSpec_Container) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoc_entity_workload_spec_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec_Container.ProtoReflect.Descriptor instead.
func (*WorkloadSpec_Container) Descriptor() ([]byte, []int) {
	return file_api_protoc_entity_workload_spec_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WorkloadSpec_Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadSpec_Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *WorkloadSpec_Container) GetResources() *WorkloadSpec_Container_Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *WorkloadSpec_Container) GetStorage() []*WorkloadSpec_Container_Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

type WorkloadSpec_Container_Resources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,numeric,gte=32,lte=65536"
	MemorySize uint32 `protobuf:"varint,1,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty" validate:"required,numeric,gte=32,lte=65536"`
	// @inject_tag: validate:"required,numeric,gte=1,lte=16"
	CpuCount uint32 `protobuf:"varint,2,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty" validate:"required,numeric,gte=1,lte=16"`
	// @inject_tag: validate:"required,numeric,gte=1000,lte=100000000"
	CpuPerformance uint32 `protobuf:"varint,3,opt,name=cpu_performance,json=cpuPerformance,proto3" json:"cpu_performance,omitempty" validate:"required,numeric,gte=1000,lte=100000000"`
}

func (x *WorkloadSpec_Container_Resources) Reset() {
	*x = WorkloadSpec_Container_Resources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protoc_entity_workload_spec_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadSpec_Container_Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec_Container_Resources) ProtoMessage() {}

func (x *WorkloadSpec_Container_Resources) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoc_entity_workload_spec_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec_Container_Resources.ProtoReflect.Descriptor instead.
func (*WorkloadSpec_Container_Resources) Descriptor() ([]byte, []int) {
	return file_api_protoc_entity_workload_spec_message_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *WorkloadSpec_Container_Resources) GetMemorySize() uint32 {
	if x != nil {
		return x.MemorySize
	}
	return 0
}

func (x *WorkloadSpec_Container_Resources) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *WorkloadSpec_Container_Resources) GetCpuPerformance() uint32 {
	if x != nil {
		return x.CpuPerformance
	}
	return 0
}

type WorkloadSpec_Container_Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: validate:"required,dir"
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty" validate:"required,dir"`
	// @inject_tag: validate:"required,uri"
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty" validate:"required,uri"`
}

func (x *WorkloadSpec_Container_Storage) Reset() {
	*x = WorkloadSpec_Container_Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protoc_entity_workload_spec_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadSpec_Container_Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec_Container_Storage) ProtoMessage() {}

func (x *WorkloadSpec_Container_Storage) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoc_entity_workload_spec_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec_Container_Storage.ProtoReflect.Descriptor instead.
func (*WorkloadSpec_Container_Storage) Descriptor() ([]byte, []int) {
	return file_api_protoc_entity_workload_spec_message_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *WorkloadSpec_Container_Storage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkloadSpec_Container_Storage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_api_protoc_entity_workload_spec_message_proto protoreflect.FileDescriptor

var file_api_protoc_entity_workload_spec_message_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x70, 0x65,
	0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x69, 0x6f, 0x2e, 0x6e, 0x61, 0x66, 0x74, 0x69, 0x73, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x1a, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb3, 0x05, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x48, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x69, 0x6f, 0x2e, 0x6e, 0x61, 0x66, 0x74, 0x69,
	0x73, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52,
	0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x46, 0x0a, 0x09, 0x69,
	0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28,
	0x2e, 0x69, 0x6f, 0x2e, 0x6e, 0x61, 0x66, 0x74, 0x69, 0x73, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x49,
	0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6f, 0x2e, 0x6e,
	0x61, 0x66, 0x74, 0x69, 0x73, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x1a, 0xfe, 0x02, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x50, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x32, 0x2e, 0x69, 0x6f, 0x2e, 0x6e, 0x61, 0x66, 0x74, 0x69, 0x73, 0x2e, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x70,
	0x65, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x12, 0x4a, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x69, 0x6f, 0x2e, 0x6e, 0x61, 0x66, 0x74, 0x69, 0x73, 0x2e, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x70,
	0x65, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x72, 0x0a,
	0x09, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x70, 0x75, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x63, 0x70, 0x75, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x70, 0x75, 0x5f,
	0x70, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0e, 0x63, 0x70, 0x75, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63,
	0x65, 0x1a, 0x35, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x4c, 0x0a, 0x09, 0x49, 0x73, 0x6f, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x5f, 0x49, 0x53, 0x4f, 0x4c,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x4f, 0x4e, 0x54, 0x41,
	0x49, 0x4e, 0x45, 0x52, 0x5f, 0x49, 0x53, 0x4f, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01,
	0x12, 0x14, 0x0a, 0x10, 0x4b, 0x45, 0x52, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x53, 0x4f, 0x4c, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x66, 0x74, 0x69, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x6e, 0x61, 0x66, 0x74, 0x69, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_protoc_entity_workload_spec_message_proto_rawDescOnce sync.Once
	file_api_protoc_entity_workload_spec_message_proto_rawDescData = file_api_protoc_entity_workload_spec_message_proto_rawDesc
)

func file_api_protoc_entity_workload_spec_message_proto_rawDescGZIP() []byte {
	file_api_protoc_entity_workload_spec_message_proto_rawDescOnce.Do(func() {
		file_api_protoc_entity_workload_spec_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protoc_entity_workload_spec_message_proto_rawDescData)
	})
	return file_api_protoc_entity_workload_spec_message_proto_rawDescData
}

var file_api_protoc_entity_workload_spec_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protoc_entity_workload_spec_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_protoc_entity_workload_spec_message_proto_goTypes = []interface{}{
	(WorkloadSpec_Isolation)(0),              // 0: io.naftis.entity.WorkloadSpec.Isolation
	(*WorkloadSpec)(nil),                     // 1: io.naftis.entity.WorkloadSpec
	(*WorkloadSpec_Container)(nil),           // 2: io.naftis.entity.WorkloadSpec.Container
	(*WorkloadSpec_Container_Resources)(nil), // 3: io.naftis.entity.WorkloadSpec.Container.Resources
	(*WorkloadSpec_Container_Storage)(nil),   // 4: io.naftis.entity.WorkloadSpec.Container.Storage
	(*NodeSelector)(nil),                     // 5: io.naftis.entity.NodeSelector
}
var file_api_protoc_entity_workload_spec_message_proto_depIdxs = []int32{
	2, // 0: io.naftis.entity.WorkloadSpec.containers:type_name -> io.naftis.entity.WorkloadSpec.Container
	0, // 1: io.naftis.entity.WorkloadSpec.isolation:type_name -> io.naftis.entity.WorkloadSpec.Isolation
	5, // 2: io.naftis.entity.WorkloadSpec.nodeSelector:type_name -> io.naftis.entity.NodeSelector
	3, // 3: io.naftis.entity.WorkloadSpec.Container.resources:type_name -> io.naftis.entity.WorkloadSpec.Container.Resources
	4, // 4: io.naftis.entity.WorkloadSpec.Container.storage:type_name -> io.naftis.entity.WorkloadSpec.Container.Storage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_protoc_entity_workload_spec_message_proto_init() }
func file_api_protoc_entity_workload_spec_message_proto_init() {
	if File_api_protoc_entity_workload_spec_message_proto != nil {
		return
	}
	file_api_protoc_entity_node_selector_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_protoc_entity_workload_spec_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protoc_entity_workload_spec_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadSpec_Container); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protoc_entity_workload_spec_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadSpec_Container_Resources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protoc_entity_workload_spec_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadSpec_Container_Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protoc_entity_workload_spec_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protoc_entity_workload_spec_message_proto_goTypes,
		DependencyIndexes: file_api_protoc_entity_workload_spec_message_proto_depIdxs,
		EnumInfos:         file_api_protoc_entity_workload_spec_message_proto_enumTypes,
		MessageInfos:      file_api_protoc_entity_workload_spec_message_proto_msgTypes,
	}.Build()
	File_api_protoc_entity_workload_spec_message_proto = out.File
	file_api_protoc_entity_workload_spec_message_proto_rawDesc = nil
	file_api_protoc_entity_workload_spec_message_proto_goTypes = nil
	file_api_protoc_entity_workload_spec_message_proto_depIdxs = nil
}
