// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: api/protoc/market/workload_specification_message.proto

package market

import (
	proto "github.com/golang/protobuf/proto"
	entity "gitlab.com/naftis/app/naftis/pkg/protocol/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// WorkloadSpecification message is published to blockchain by Principal side. This message contains expected
// Runner capabilities and runtime parameters. This message MUST be published before ContractRequest, because
// ContractRequest referencing this specification.
type WorkloadSpecification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec               *entity.WorkloadSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	PrincipalPublicKey string               `protobuf:"bytes,2,opt,name=principal_public_key,json=principalPublicKey,proto3" json:"principal_public_key,omitempty"` // ECDSA
}

func (x *WorkloadSpecification) Reset() {
	*x = WorkloadSpecification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protoc_market_workload_specification_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpecification) ProtoMessage() {}

func (x *WorkloadSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoc_market_workload_specification_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpecification.ProtoReflect.Descriptor instead.
func (*WorkloadSpecification) Descriptor() ([]byte, []int) {
	return file_api_protoc_market_workload_specification_message_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadSpecification) GetSpec() *entity.WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *WorkloadSpecification) GetPrincipalPublicKey() string {
	if x != nil {
		return x.PrincipalPublicKey
	}
	return ""
}

var File_api_protoc_market_workload_specification_message_proto protoreflect.FileDescriptor

var file_api_protoc_market_workload_specification_message_proto_rawDesc = []byte{
	0x0a, 0x36, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x69, 0x6f, 0x2e, 0x6e, 0x61, 0x66,
	0x74, 0x69, 0x73, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x1a, 0x2d, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x77, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x15, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x69, 0x6f, 0x2e, 0x6e, 0x61, 0x66, 0x74, 0x69, 0x73, 0x2e, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x70, 0x65, 0x63,
	0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x30, 0x0a, 0x14, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69,
	0x70, 0x61, 0x6c, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x66, 0x74, 0x69, 0x73, 0x2f, 0x61, 0x70,
	0x70, 0x2f, 0x6e, 0x61, 0x66, 0x74, 0x69, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protoc_market_workload_specification_message_proto_rawDescOnce sync.Once
	file_api_protoc_market_workload_specification_message_proto_rawDescData = file_api_protoc_market_workload_specification_message_proto_rawDesc
)

func file_api_protoc_market_workload_specification_message_proto_rawDescGZIP() []byte {
	file_api_protoc_market_workload_specification_message_proto_rawDescOnce.Do(func() {
		file_api_protoc_market_workload_specification_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protoc_market_workload_specification_message_proto_rawDescData)
	})
	return file_api_protoc_market_workload_specification_message_proto_rawDescData
}

var file_api_protoc_market_workload_specification_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_protoc_market_workload_specification_message_proto_goTypes = []interface{}{
	(*WorkloadSpecification)(nil), // 0: io.naftis.market.WorkloadSpecification
	(*entity.WorkloadSpec)(nil),   // 1: io.naftis.entity.WorkloadSpec
}
var file_api_protoc_market_workload_specification_message_proto_depIdxs = []int32{
	1, // 0: io.naftis.market.WorkloadSpecification.spec:type_name -> io.naftis.entity.WorkloadSpec
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_protoc_market_workload_specification_message_proto_init() }
func file_api_protoc_market_workload_specification_message_proto_init() {
	if File_api_protoc_market_workload_specification_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protoc_market_workload_specification_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadSpecification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protoc_market_workload_specification_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protoc_market_workload_specification_message_proto_goTypes,
		DependencyIndexes: file_api_protoc_market_workload_specification_message_proto_depIdxs,
		MessageInfos:      file_api_protoc_market_workload_specification_message_proto_msgTypes,
	}.Build()
	File_api_protoc_market_workload_specification_message_proto = out.File
	file_api_protoc_market_workload_specification_message_proto_rawDesc = nil
	file_api_protoc_market_workload_specification_message_proto_goTypes = nil
	file_api_protoc_market_workload_specification_message_proto_depIdxs = nil
}
